### ISSUE TITLE
Whether the training parameters depend on the camera settings

### ISSUE THREAD

**Issue by hodakag** [ztsrxh/DVANet#2]
Hi, since the normalized depths don't consider the camera settings, I guess all training and test data should have the same focal length and baseline. Is my understanding correct?

**Comment by ztsrxh** [comment]
You get it. The normalized depth map is derived by setting the minimum disparity or maximum depth of the dataset. This is a general statistical value and should be set for every target dataset.

**Comment by hodakag** [comment]
Understood. Thank you.
